//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Complaints = new HashSet<Complaint>();
            this.EmployeeStatus = new HashSet<EmployeeStatu>();
            this.Reviews = new HashSet<Review>();
            this.SickLeaves = new HashSet<SickLeave>();
            this.Vacations = new HashSet<Vacation>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string EmployeePassword { get; set; }
        public string Email { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> VacationDays { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> SickDaysTotal { get; set; }
        public int DepartmentId { get; set; }
        public int EmployeeStatusId { get; set; }
        public Nullable<int> NumberOfReviews { get; set; }
        public Nullable<int> Standing { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string CurrentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeStatu> EmployeeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SickLeave> SickLeaves { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacation> Vacations { get; set; }
    }
}
