//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStatu
    {
        public int EmployeeStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TreminationDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public string CurrentStatus { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
